// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package oldqueries

import (
	"database/sql"
)

type Items struct {
	ID              int64
	Code            string
	CodeType        sql.NullString
	Location        sql.NullString
	Title           sql.NullString
	DataSource      sql.NullString
	Comments        sql.NullString
	Created         sql.NullTime
	TitleTranslated sql.NullString
}
