version: '3.8'
services:
  library:
    container_name: library-api
    image: ghcr.io/klaital/library-api:latest
    restart: unless-stopped
    ports:
      - 10001:8080
    environment:
      - DB_FILE=/prod.db
    volumes:
      - ${PWD}/prod.db:/prod.db:rw,delegated

